"""
Configuration file for the Swing Trading application.
Contains all strategy parameters and settings.
"""

class Config:
    """Configuration class containing all trading strategy parameters."""
    
    # Stock symbols (NSE symbols)
    STOCK_SYMBOLS = [
    'ABB.NS',
    'ACC.NS',
    'APLAPOLLO.NS',
    'AUBANK.NS',
    'ADANIENSOL.NS',
    'ADANIENT.NS',
    'ADANIGREEN.NS',
    'ADANIPORTS.NS',
    'ADANIPOWER.NS',
    'ATGL.NS',
    'ABCAPITAL.NS',
    'ABFRL.NS',
    'ALKEM.NS',
    'AMBUJACEM.NS',
    'APOLLOHOSP.NS',
    'APOLLOTYRE.NS',
    'ASHOKLEY.NS',
    'ASIANPAINT.NS',
    'ASTRAL.NS',
    'AUROPHARMA.NS',
    'DMART.NS',
    'AXISBANK.NS',
    'BSE.NS',
    'BAJAJ-AUTO.NS',
    'BAJFINANCE.NS',
    'BAJAJFINSV.NS',
    'BAJAJHLDNG.NS',
    'BAJAJHFL.NS',
    'BANDHANBNK.NS',
    'BANKBARODA.NS',
    'BANKINDIA.NS',
    'MAHABANK.NS',
    'BDL.NS',
    'BEL.NS',
    'BHARATFORG.NS',
    'BHEL.NS',
    'BPCL.NS',
    'BHARTIARTL.NS',
    'BHARTIHEXA.NS',
    'BIOCON.NS',
    'BOSCHLTD.NS',
    'BRITANNIA.NS',
    'CGPOWER.NS',
    'CANBK.NS',
    'CHOLAFIN.NS',
    'CIPLA.NS',
    'COALINDIA.NS',
    'COCHINSHIP.NS',
    'COFORGE.NS',
    'COLPAL.NS',
    'CONCOR.NS',
    'CUMMINSIND.NS',
    'DLF.NS',
    'DABUR.NS',
    'DIVISLAB.NS',
    'DIXON.NS',
    'DRREDDY.NS',
    'EICHERMOT.NS',
    'ESCORTS.NS',
    'ETERNAL.NS',
    'EXIDEIND.NS',
    'NYKAA.NS',
    'FEDERALBNK.NS',
    'GAIL.NS',
    'GMRAIRPORT.NS',
    'GLENMARK.NS',
    'GODREJCP.NS',
    'GODREJPROP.NS',
    'GRASIM.NS',
    'HCLTECH.NS',
    'HDFCAMC.NS',
    'HDFCBANK.NS',
    'HDFCLIFE.NS',
    'HAVELLS.NS',
    'HEROMOTOCO.NS',
    'HINDALCO.NS',
    'HAL.NS',
    'HINDPETRO.NS',
    'HINDUNILVR.NS',
    'HINDZINC.NS',
    'HUDCO.NS',
    'HYUNDAI.NS',
    'ICICIBANK.NS',
    'ICICIGI.NS',
    'ICICIPRULI.NS',
    'IDFCFIRSTB.NS',
    'IRB.NS',
    'ITC.NS',
    'INDIANB.NS',
    'INDHOTEL.NS',
    'IOC.NS',
    'IRCTC.NS',
    'IRFC.NS',
    'IREDA.NS',
    'IGL.NS',
    'INDUSTOWER.NS',
    'INDUSINDBK.NS',
    'NAUKRI.NS',
    'INFY.NS',
    'INDIGO.NS',
    'JSWENERGY.NS',
    'JSWSTEEL.NS',
    'JINDALSTEL.NS',
    'JIOFIN.NS',
    'JUBLFOOD.NS',
    'KPITTECH.NS',
    'KALYANKJIL.NS',
    'KOTAKBANK.NS',
    'LTF.NS',
    'LICHSGFIN.NS',
    'LTIM.NS',
    'LT.NS',
    'LICI.NS',
    'LODHA.NS',
    'LUPIN.NS',
    'MRF.NS',
    'M&MFIN.NS',
    'M&M.NS',
    'MANKIND.NS',
    'MARICO.NS',
    'MARUTI.NS',
    'MFSL.NS',
    'MAXHEALTH.NS',
    'MAZDOCK.NS',
    'MOTILALOFS.NS',
    'MPHASIS.NS',
    'MUTHOOTFIN.NS',
    'NHPC.NS',
    'NMDC.NS',
    'NTPCGREEN.NS',
    'NTPC.NS',
    'NATIONALUM.NS',
    'NESTLEIND.NS',
    'OBEROIRLTY.NS',
    'ONGC.NS',
    'OIL.NS',
    'OLAELEC.NS',
    'PAYTM.NS',
    'OFSS.NS',
    'POLICYBZR.NS',
    'PIIND.NS',
    'PAGEIND.NS',
    'PATANJALI.NS',
    'PERSISTENT.NS',
    'PETRONET.NS',
    'PHOENIXLTD.NS',
    'PIDILITIND.NS',
    'POLYCAB.NS',
    'PFC.NS',
    'POWERGRID.NS',
    'PREMIERENE.NS',
    'PRESTIGE.NS',
    'PNB.NS',
    'RECLTD.NS',
    'RVNL.NS',
    'RELIANCE.NS',
    'SBICARD.NS',
    'SBILIFE.NS',
    'SJVN.NS',
    'SRF.NS',
    'MOTHERSON.NS',
    'SHREECEM.NS',
    'SHRIRAMFIN.NS',
    'SIEMENS.NS',
    'SOLARINDS.NS',
    'SONACOMS.NS',
    'SBIN.NS',
    'SAIL.NS',
    'SUNPHARMA.NS',
    'SUPREMEIND.NS',
    'SUZLON.NS',
    'SWIGGY.NS',
    'TVSMOTOR.NS',
    'TATACOMM.NS',
    'TCS.NS',
    'TATACONSUM.NS',
    'TATAELXSI.NS',
    'TATAMOTORS.NS',
    'TATAPOWER.NS',
    'TATASTEEL.NS',
    'TATATECH.NS',
    'TECHM.NS',
    'TITAN.NS',
    'TORNTPHARM.NS',
    'TORNTPOWER.NS',
    'TRENT.NS',
    'TIINDIA.NS',
    'UPL.NS',
    'ULTRACEMCO.NS',
    'UNIONBANK.NS',
    'UNITDSPR.NS',
    'VBL.NS',
    'VEDL.NS',
    'VMM.NS',
    'IDEA.NS',
    'VOLTAS.NS',
    'WAAREEENER.NS',
    'WIPRO.NS',
    'YESBANK.NS',
    'ZYDUSLIFE.NS'
]
    
    # DMA (Displaced Moving Average) windows
    DMA_WINDOWS = [20, 50, 100, 200]
    
    # Volume multiplier threshold
    VOLUME_MULTIPLIER = 1.5
    
    # RSI parameters
    RSI_WINDOW = 14
    RSI_THRESHOLD = 60
    
    # 52-week high proximity threshold (98% of 52-week high)
    WEEK_52_HIGH_PROXIMITY = 0.98
    
    # Risk per trade in INR
    RISK_PER_TRADE = 1000
    
    # Flask configuration
    SECRET_KEY = 'your-secret-key-change-this-in-production'
    DEBUG = True

# Create a dictionary version for easy access
STRATEGY_PARAMS = {
    'stock_symbols': Config.STOCK_SYMBOLS,
    'dma_windows': Config.DMA_WINDOWS,
    'volume_multiplier': Config.VOLUME_MULTIPLIER,
    'rsi_window': Config.RSI_WINDOW,
    'rsi_threshold': Config.RSI_THRESHOLD,
    'week_52_high_proximity': Config.WEEK_52_HIGH_PROXIMITY,
    'risk_per_trade': Config.RISK_PER_TRADE
}
